name: capture
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pip:
      - pytest-playwright
# to install browser binaries run: playwright install chromium
